g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o sf2.o sf2.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o zdt6.o zdt6.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o kur.o kur.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o okk.o okk.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o init.o init.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rand.o rand.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o intgene.o intgene.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o realgene.o realgene.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o genome.o genome.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o fitness.o fitness.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ffunction.o ffunction.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o individual.o individual.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o initiator.o initiator.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o population.o population.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o moperator.o moperator.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o umutation.o umutation.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o nmutation.o nmutation.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o pmutation.o pmutation.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o amutation.o amutation.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o soperator.o soperator.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o tselection.o tselection.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o coperator.o coperator.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ucrossover.o ucrossover.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o nucrossover.o nucrossover.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o sbcrossover.o sbcrossover.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ealgorithm.o ealgorithm.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o attribute.o attribute.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o attributes.o attributes.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rattribute.o rattribute.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o iattribute.o iattribute.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o value.o value.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ivalue.o ivalue.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rvalue.o rvalue.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o instance.o instance.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o instances.o instances.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o afitness.o afitness.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o asfitness.o asfitness.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o asgfitness.o asgfitness.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ascfitness.o ascfitness.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o cffunction.o cffunction.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o dmaker.o dmaker.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o baccuracy.o baccuracy.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o bcompromise.o bcompromise.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o mselection.o mselection.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o nnmating.o nnmating.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o fpmating.o fpmating.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rmating.o rmating.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o tmating.o tmating.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o iloader.o iloader.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o arff.o arff.cc
bison -d -parff_ -barff arff.y
mv arff.tab.c arff.tab.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o arff.tab.o arff.tab.cc
flex -i -Parff_ -oarff.yy.cc arff.lex
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o arff.yy.o arff.yy.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o model.o model.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rmodel.o rmodel.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o imodel.o imodel.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o mmodel.o mmodel.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rrmodel.o rrmodel.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o element.o element.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rrelement.o rrelement.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rielement.o rielement.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o irelement.o irelement.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o iielement.o iielement.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o rinit.o rinit.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o iinit.o iinit.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o moga.o moga.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o moes.o moes.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o ngga.o ngga.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o nsgaii.o nsgaii.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o spea2.o spea2.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o moea.o moea.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o mocs.o mocs.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o loader.o loader.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o loadable.o loadable.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o params.o params.cc
bison -d -pparams_ -bparams params.y
mv params.tab.c params.tab.cc
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o params.tab.o params.tab.cc
flex -i -Pparams_ -oparams.yy.cc params.lex
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o params.yy.o params.yy.cc
g++ -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -fpic -rdynamic -shared -o libmocs.so sf2.o zdt6.o kur.o okk.o init.o rand.o intgene.o realgene.o genome.o fitness.o ffunction.o individual.o initiator.o population.o moperator.o umutation.o nmutation.o pmutation.o amutation.o soperator.o tselection.o coperator.o ucrossover.o nucrossover.o sbcrossover.o ealgorithm.o attribute.o attributes.o rattribute.o iattribute.o value.o ivalue.o rvalue.o instance.o instances.o afitness.o asfitness.o asgfitness.o ascfitness.o cffunction.o dmaker.o baccuracy.o bcompromise.o mselection.o nnmating.o fpmating.o rmating.o tmating.o iloader.o arff.o arff.tab.o arff.yy.o model.o rmodel.o imodel.o mmodel.o rrmodel.o element.o rrelement.o rielement.o irelement.o iielement.o rinit.o iinit.o moga.o moes.o ngga.o nsgaii.o spea2.o moea.o mocs.o loader.o loadable.o params.o params.tab.o params.yy.o
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o imoea.o imoea.cc
g++ -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -fpic -rdynamic -o imoea imoea.o  -lm -ldl -L. -lmocs
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o imocs.o imocs.cc
g++ -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -fpic -rdynamic -o imocs imocs.o  -lm -ldl -L. -lmocs
g++ -c -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -o metrics.o metrics.cc
g++ -I. -Wall -Wstrict-prototypes -Wdeprecated -Wno-long-long -Wmissing-prototypes -Wredundant-decls -ansi -pedantic -pipe -O3 -fexpensive-optimizations -fomit-frame-pointer -funroll-loops -ffast-math  -fpic -rdynamic  -fpic -rdynamic -o metrics metrics.o  -lm -ldl -L. -lmocs
